version: '3'

services:
  db:
    image: mongo:4
    ports:
      - '27018:27017'

  api:
    build:
      context: ./api
      args:
        - NODE_ENV=production
        - PORT=1666
    command: nodemon -L
    env_file:
      - ./api/.env
    ports:
      - 1666:1666
    volumes:
      - ./api:/opt/app
      - ./api:/opt/app/node_modules
    links:
      - db
    depends_on:
      - db
